/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cn.edu.njupt.clock;

import javax.sound.sampled.*;
import javax.swing.*;
import java.awt.*;
import java.io.IOException;
import java.util.concurrent.Executors;

/**
 *
 * @author gaofan
 */
public class AlarmDialog extends JDialog {

    /**
     * Creates new form AlarmDialog
     */
    public AlarmDialog(Frame parent, boolean modal) {
        super(parent, modal);
        setTitle("闹钟");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRemind = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonRemind.setLabel("稍后提醒");

        jButtonClose.setLabel("结束");

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 105, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonRemind, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRemind)
                .addGap(1, 1, 1)
                .addComponent(jButtonClose))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int result = 0;
    public static int create(JFrame parent) {
        AlarmDialog dialog = new AlarmDialog(parent, true);
        Executors.newFixedThreadPool(1).execute(() ->{
            while(dialog.isVisible()){
                try {
                    // 播放声音
                    AudioInputStream audioIn = AudioSystem.getAudioInputStream(Alarm.class.getClassLoader().getResource("sound/test.wav"));
                    Clip clip = AudioSystem.getClip();
                    clip.open(audioIn);
                    clip.start();
                } catch (LineUnavailableException | IOException | UnsupportedAudioFileException e) {
                    e.printStackTrace();
                }
            }
        });
        dialog.jButtonRemind.addActionListener(e -> {
            dialog.result = 0;
            dialog.setVisible(false);
            dialog.dispose();
        });
        dialog.jButtonClose.addActionListener(e -> {
            dialog.result = 1;
            dialog.setVisible(false);
            dialog.dispose();
        });
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                dialog.result = 0;
            }
        });

        dialog.setLocationRelativeTo(parent);
        dialog.setVisible(true);
        return dialog.result;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRemind;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
